sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "sudo ./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sudo sfdx --version
- sudo sfdx plugins --core
- sudo sfdx force:auth:jwt:grant --clientid "3MVG9Kip4IKAZQEXPqFhpHnJPaRxAiPNBEwujMLruGalgr0onAqLJmujLMie_l.rC94naSQiQcRzGMaxptwW2" --jwtkeyfile assets/server.key --username "murilo.conde@wise-panda-rv27f0.com" --setdefaultdevhubusername -a HubOrg
script:
- sudo sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sudo sfdx force:org:display -u ciorg
- sudo sfdx force:source:push -u ciorg
- sudo sfdx force:apex:test:run -u ciorg --wait 10
- sudo sfdx force:org:delete -u ciorg -p
